"""Generate a PyInstaller Windows version resource (version_info.txt) from the
single source of truth, the VERSION file.

An unsigned, version-LESS one-file exe is exactly the profile Windows Defender
SmartScreen and AV engines flag ("Windows protected your PC"), which makes the
app "fail to run" on a user's laptop while it runs on the developer's. Stamping a
real version resource gives reputation heuristics a legitimate signal. (Proper
Authenticode signing is still the strongest fix; do that too if a cert exists.)

Run from the repo root (compile_windows.bat does this automatically):
    python make_version_info.py
"""

import os

HERE = os.path.dirname(os.path.abspath(__file__))


def read_version():
    try:
        with open(os.path.join(HERE, 'VERSION'), 'r', encoding='utf-8') as f:
            return f.read().strip() or '1.1'
    except Exception:
        return '1.1'


def version_tuple(v):
    parts = (v.replace('-', '.').split('.') + ['0', '0', '0', '0'])[:4]
    return tuple(int(p) if p.isdigit() else 0 for p in parts)


TEMPLATE = """\
# Auto-generated by make_version_info.py from VERSION ({vstr}). Do not edit by hand.
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers={vt},
    prodvers={vt},
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0)
  ),
  kids=[
    StringFileInfo([
      StringTable(
        '040904B0',
        [
          StringStruct('CompanyName', 'Bluesun'),
          StringStruct('FileDescription', 'Video Tiler'),
          StringStruct('FileVersion', '{vstr}'),
          StringStruct('InternalName', 'video-tiler'),
          StringStruct('OriginalFilename', 'video-tiler.exe'),
          StringStruct('ProductName', 'Video Tiler'),
          StringStruct('ProductVersion', '{vstr}'),
          StringStruct('LegalCopyright', 'Bluesun')
        ])
    ]),
    VarFileInfo([VarStruct('Translation', [1033, 1200])])
  ]
)
"""


def main():
    v = read_version()
    vt = version_tuple(v)
    vstr = '.'.join(str(x) for x in vt)
    out = os.path.join(HERE, 'version_info.txt')
    with open(out, 'w', encoding='utf-8') as f:
        f.write(TEMPLATE.format(vt=vt, vstr=vstr))
    print("wrote {} (version {})".format(out, vstr))


if __name__ == '__main__':
    main()
